ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views

app_name="cart"
urlpatterns = [
    path('cart/<int:i>', views.cart, name="cart"),
    path('cart_view', views.cart_view, name="cart_view"),
    path('cart_remove/<int:i>', views.cart_remove, name="cart_remove"),
    path('cart_delete/<int:i>', views.cart_delete, name="cart_delete"),
    path('order_form/', views.order_form, name="order_form"),
    path('payment_status/<u>', views.payment_status, name="payment_status"),
    path('order_view', views.order_view, name="order_view"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from django.conf.urls.static import static
from django.conf import settings

app_name='shop'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.categories,name="categories"),
    path('register',views.registration,name="registration"),
    path('login',views.user_login,name="user_login"),
    path('logout',views.user_logout,name="user_logout"),
    path('products/<int:p>',views.products,name="products"),
    path('product_details/<int:p>',views.product_details,name="product_details"),
    path('add_categories', views.add_categories, name="add_categories"),
    path('add_product', views.add_product, name="add_product"),
    path('add_stock/<int:i>', views.add_stock, name="add_stock"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)


class Order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.CharField(max_length=20)
    phone=models.BigIntegerField()
    pin=models.IntegerField()
    order_id=models.CharField(max_length=30)
    ordered_date=models.DateTimeField(auto_now_add=True)
    payment_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product,Category
from cart.models import Cart
from cart.models import Payment
from cart.models import Order_details
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import razorpay
# Create your views here.

@login_required
def cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(product=p,user=u)
        if p.stock>0 :
            c.quantity+=1
            c.save()
            p.stock=1
            p.save()
    except:
        if p.stock>0:
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock-=1
            p.save()

    return redirect('cart:cart_view')
    # return render(request,'cart.html')
@login_required
def cart_view(request):
    u=request.user
    c=Cart.objects.filter(user=u)
    total=0
    for i in c:

        total+=i.quantity*i.product.price
    context={'cart':c,'total':total}
    return render(request,'cart.html',context)

@login_required
def cart_remove(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        c = Cart.objects.get(product=p, user=u)
        if c.quantity > 1:
            c.quantity -= 1
            c.save()
            p.stock = 1
            p.save()

        else:
            c.delete()
            p.stock +=1
            p.save()
    except:
        pass
    return redirect('cart:cart_view')

@login_required
def cart_delete(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        c = Cart.objects.get(product=p, user=u)
        c.delete()
        p.stock += c.quantity
    except:
        pass
    return redirect('cart:cart_view')

@login_required
def order_form(request):
    if request.method=="POST":
        address=request.POST['a']
        phone=request.POST['ph']
        pin=request.POST['pin']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total1=int(total*100)


        client=razorpay.Client(auth=('rzp_test_ltFWpuZG17IABK','QSjwh84KzZZVehHQDCLbf4bq')) # create a client connection
        # using razopay id and secrete code
        response_payment=client.order.create(dict(amount=total1,currency="INR"))  #create an order with
        # razopay using razpay client
        print(response_payment)
        order_id=response_payment['id']   #retrives the order_id from respones
        order_status=response_payment['status']   #retrives sts from respones
        if(order_status=="created"):   #if status is created then store order_id in Pymnt and Order_details table
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:   #For each item creates a record inside Order_details table
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone=phone,pin=pin,order_id=order_id)
                o.save()
        response_payment['name']=u.username
        context={'payment':response_payment}
        return render(request,'payment.html',context)

    return render(request,'order_form.html')


from django.contrib.auth import login
@csrf_exempt
def payment_status(request,u):

    u = User.objects.get(username=u)
    if not request.user.is_authenticated:
         login(request,u)

    if(request.method=="POST"):
        response=request.POST
        print(response)

        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature'],
        }

        # To check the authenticity of razorpay signature

        client = razorpay.Client(auth=('rzp_test_ltFWpuZG17IABK', 'QSjwh84KzZZVehHQDCLbf4bq'))
        print(client)
        try:
            status=client.utility.verify_payment_signature(param_dict)
            print(status)

            # To retrieve a particular record form Payment Table matching with razorpay response order id
            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id=response['razorpay_payment_id']
            p.paid=True
            p.save()

            # To retrieve a records form Order_details Table matching with razorpay response order id

            o=Order_details.objects.filter(order_id=response['razorpay_order_id'])
            for i in o:
                i.payment_status="completed"
                i.save()

                c=Cart.objects.filter(user=u)
                c.delete()

        except:
            pass
    return render(request,'payment_status.html',{'status':status})


@login_required
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u)
    context={"orders":o}
    return render(request,'order_view.html',context)

ecommerce/templates/add_categories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<h2 class= "text-center my-2 fw-bold " style="font-family: EamesBold;">Add Category Details</h2>
<form method="POST" enctype="multipart/form-data" class="mx-4">
  {% csrf_token %}
<div class=" mx-2">
  <label  class="form-label">Name :</label>
  <input type="text" class="form-control" name="n" placeholder="name">
</div>
<div class="mb-3 mx-2">
  <label  class="form-label">Image :</label>
  <input type="file" class="form-control" name="i" placeholder="image">
</div>
<div class="mb-3 mx-2">
  <label  class="form-label">Description :</label>
  <textarea class="form-control" name="d" placeholder="description"></textarea>
</div>
<div class=" mx-2">
<input type="submit" class="form-control" value="Submit">
</div>
</form>
</section>
{% endblock %}

ecommerce/templates/add_stock.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">
<div class="container-fluid mx-5 ">
<h2 class="text-center my-3 fw-bold"  style="font-family: EamesBold;">Add Stock</h2>
<form method="POST" enctype="multipart/form-data" class="mx-4">
  {% csrf_token %}
<div class=" mx-3 my-2">
  <input type="number" class="form-control" value="{{product.stock}}" name="n" placeholder="stock">
</div>


<div class=" mx-3">
<input type="submit" class="form-control">
</div>
</form>
</div>
</section>

{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">
<div class="container">
    <div class="row">
        <h2 class="text-center fw-bold mb-5"  style="font-family: EamesBold;">Shopping Now</h2>
        <div class="col-7">
            <table class="table table-bordered text-center">
                <tr><th colspan="7">Cart items</th></tr>
                {%  for i in cart %}
                <tr>
                    <td><img src="{{i.product.image.url}}" width="150px"></td>
                    <td>Product: {{i.product.name}}</td>
                    <td>price : {{i.product.price}}<br>
                    Quantity :{{i.quantity}}</td>
                    <td>subtotal :{{i.subtotal}}</td>
                    <td>
                            {% if i.product.stock > 0 %}
                            <a href="{% url 'cart:cart' i.product.id %}"><i class="fa-solid fa-circle-plus text-dark"></i></a>
                            <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus text-dark"></i></a>
                            <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash-can text-dark"></i></a>
                            {% else %}
                            <a href="{% url 'cart:cart' i.product.id %}"><i class="fa-solid fa-circle-plus text-dark"></i></a>
                            <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus text-dark"></i></a>
                            <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash-can text-dark"></i></a>
                            {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
         <div class="col-4">
             <table class="table table-bordered text-center">
                 <tr><th colspan="3">Check out</th></tr>
                 <tr><th colspan="3">Total price : {{total}}</th></tr>
             </table>
             <div class="d-flex justify-content-between">
                <a href="{% url 'cart:order_form' %}" class="btn btn-outline-secondary ">Order now</a>
                <a href="" class="btn btn-outline-secondary ">continue to shopping</a>
            </div>
         </div>
    </div>
</div>
</section>
{% endblock %}

ecommerce/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--<style>-->

<!--.category-carousel .category-item {-->
<!--    transition: box-shadow 0.3s ease-out, transform 0.3s ease-out;-->
<!--    }-->
<!--</style>-->

   <section class="py-3" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size: cover;">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">

            <div class="banner-blocks">

              <div class="banner-ad large bg-info block-1">

                <div class="swiper main-swiper">
                  <div class="swiper-wrapper">

                    <div class="swiper-slide">
                      <div class="row banner-content p-5">
                        <div class="content-wrapper col-md-7">
                          <div class="categories my-3">100% natural</div>
                          <h3 class="display-4"  style="font-family: EamesBold;">Fresh Smoothie & Summer Juice</h3>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim massa diam elementum.</p>
<!--                          <a href="#" class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1 px-4 py-3 mt-3 ">Shop Now</a>-->
                        </div>
                        <div class="img-wrapper col-md-5">
                          <img src="{% static 'images/product-thumb-1.png' %}" class="img-fluid">
                        </div>
                      </div>
                    </div>

<!--                    <div class="swiper-slide">-->
<!--                      <div class="row banner-content p-5">-->
<!--                        <div class="content-wrapper col-md-7">-->
<!--                          <div class="categories mb-3 pb-3">100% natural</div>-->
<!--                          <h3 class="banner-title">Fresh Smoothie & Summer Juice</h3>-->
<!--                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim massa diam elementum.</p>-->
<!--                          <a href="#" class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1">Shop Collection</a>-->
<!--                        </div>-->
<!--                        <div class="img-wrapper col-md-5">-->
<!--                          <img src="{% static 'images/product-thumb-1.png' %}" class="img-fluid">-->
<!--                        </div>-->
<!--                      </div>-->
<!--                    </div>-->

<!--                    <div class="swiper-slide">-->
<!--                      <div class="row banner-content p-5">-->
<!--                        <div class="content-wrapper col-md-7">-->
<!--                          <div class="categories mb-3 pb-3">100% natural</div>-->
<!--                          <h3 class="banner-title">Heinz Tomato Ketchup</h3>-->
<!--                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim massa diam elementum.</p>-->
<!--                          <a href="#" class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1">Shop Collection</a>-->
<!--                        </div>-->
<!--                        <div class="img-wrapper col-md-5">-->
<!--                          <img src="{% static 'images/product-thumb-2.png' %}" class="img-fluid">-->
<!--                        </div>-->
<!--                      </div>-->
<!--                    </div>-->
                  </div>
                  <div class="swiper-pagination"></div>
                </div>
              </div>


              <div class="banner-ad bg-success-subtle block-2" style="background:url('{% static "images/ad-image-1.png" %}') no-repeat;background-position: right bottom">
                <div class="row banner-content p-5">
                  <div class="content-wrapper col-md-7">
                    <div class="categories sale mb-3 pb-3">20% off</div>
                    <h3 class="banner-title "  style="font-family: EamesBold;">Fruits & Vegetables</h3>
<!--                    <a href="#" class="d-flex align-items-center nav-link text-dark">Shop Collection <svg width="24" height="24"><use xlink:href="#arrow-right"></use></svg></a>-->
                  </div>
                </div>
              </div>


              <div class="banner-ad bg-danger block-3" style="background:url('{% static "images/ad-image-2.png" %}') no-repeat;background-position: right bottom">
                <div class="row banner-content p-5">
                  <div class="content-wrapper col-md-7">
                    <div class="categories sale mb-3 pb-3">15% off</div>
                    <h3 class="item-title"  style="font-family: EamesBold;">Baked Products</h3>
<!--                    <a href="#" class="d-flex align-items-center nav-link text-dark">Shop Collection <svg width="24" height="24"><use xlink:href="#arrow-right"></use></svg></a>-->
                  </div>
                </div>
            </div>
          </div>
        </div>

<!--            &lt;!&ndash; / Banner Blocks &ndash;&gt;-->

   </section>


<div class="container mt-3 p-2" style="margin-bottom:100px;">
<h2 class="text-center text-secondary"  style="font-family: EamesBold;">Our Collection
</h2>
<p  style="text-align:justify;line-height:2;font-size:22px;">
    There are many variations of passages of Lorem Ipsum available,
    but the majority have suffered alteration in some form, by injected humour,
    or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum,
    you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary,
    making this the first true generator on the Internet.
</p>
</div>

    <section id="latest-blog" class="py-5">
      <div class="container-fluid">
        <div class="row">
          <div class="section-header d-flex align-items-center justify-content-between my-5">
            <h2 class="section-title"  style="font-family: EamesBold;">Our Recent Blog</h2>
<!--            <div class="btn-wrap align-right">-->
<!--&lt;!&ndash;              <a href="#" class="d-flex align-items-center nav-link text-dark">Read All Articles <svg width="24" height="24"><use xlink:href="#arrow-right"></use></svg></a>&ndash;&gt;-->
<!--            </div>-->
          </div>
        </div>
        <div class="row">
{% for i in category %}
          <div class="col-md-4">
            <article class="post-item card border-0 shadow-sm p-3 my-2">
              <div class="image-holder zoom-effect">
                <a href="{% url 'shop:products' i.id %}">
                  <img src="{{i.image.url}}" alt="post" class="card-img-top" height="300px">
                </a>
              </div>
              <div class="card-body text-center">
<!--                <div class="post-meta d-flex text-uppercase gap-3 my-2 align-items-center">-->
<!--                  <div class="meta-date"><svg width="16" height="16"><use xlink:href="#calendar"></use></svg>22 Aug 2021</div>-->
<!--                  <div class="meta-categories"><svg width="16" height="16"><use xlink:href="#category"></use></svg>tips & tricks</div>-->
<!--                </div>-->
                <div class="post-header">
                  <h3 class="post-title"  style="font-family: EamesBold;">{{i.name}}
<!--                    <a href="#" class="text-decoration-none">Top 10 casual look ideas to dress up your kids</a>-->
                  </h3>
<!--                  <p>{{i.description}}</p>-->

                    <a href="{% url 'shop:products' i.id %}" class="btn btn-outline-secondary ">Products</a>
                </div>
              </div>
            </article>
          </div>
{% endfor %}
        </div>

      </div>
    </section>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<h2 class="text-center my-3 fw-bold"  style="font-family: EamesBold;">LOGIN</h2>
<form method="POST" enctype="multipart/form-data" class="mx-4">
  {% csrf_token %}
<div class="mb-3 mx-2">
  <label  class="form-label">Username :</label>
  <input type="text" class="form-control" name="u" placeholder="username">
</div>
<div class="mb-3 mx-2">
  <label  class="form-label">Password :</label>
  <input type="password" class="form-control" name="p" placeholder="password">
</div>
<div class=" mx-2">
<input type="submit" class="form-control" value="Login">
</div>
</form>
</section>
{% endblock %}

ecommerce/templates/order_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<h2 class="text-center my-2 fw-bold"  style="font-family: EamesBold;">BILLING DETAILS...</h2>
<form method="POST" enctype="multipart/form-data" class="mx-4">
  {% csrf_token %}
<div class=" mx-2">
  <label  class="form-label">Address :</label>
  <input type="text" class="form-control" name="a" placeholder="Address">
</div>
<div class="mb-3 mx-2">
  <label  class="form-label">Phone number :</label>
  <input type="number" class="form-control" name="ph" placeholder="phone number">
</div>
<div class="mb-3 mx-2">
  <label  class="form-label">Pin :</label>
  <input type="password" class="form-control" name="pin" placeholder="Pin">
</div>

<div class=" mx-2">
<input type="submit" class="form-control" value="Submit">
</div>
</form>
</section>
{% endblock %}

ecommerce/templates/order_view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

  <h2 class="text-center text-muted"  style="font-family: EamesBold;">Order Details</h2>
    {% for i in orders %}
    <div class="card mb-3 mx-auto" style="max-width: 480px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.product.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-title">Product : {{i.product.name}}</p>
        <p class="card-text">Price: {{i.product.price}}</p>
        <p class="card-text">Quantity : {{i.no_of_items}}</p>
        <p class="card-text">Ordered no : {{i.ordered_date}}</p>
        <p class="card-text">Ordered id : {{i.order_id}}</p>
        <p class="card-text">Delivery status : {{i.delivery_status}}</p>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
</section>
{% endblock %}

ecommerce/templates/payment.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px">
   <form action="{% url 'cart:payment_status' payment.name %}" class="fs-4 text-center fs-5" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_ltFWpuZG17IABK"  // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="FoodMart"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>
</section>
{% endblock %}

ecommerce/templates/payment_status.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px">
    {% if status == True %}
    <h2  style="font-family: EamesBold;">Payment successful</h2>
    {% else %}
    <h2  style="font-family: EamesBold;">Payment Failed. Try again Later
    </h2>
    {% endif %}
</div>
</section>
{% endblock %}

ecommerce/templates/product_details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<div class="card mb-3 mx-auto my-3" style="max-width: 740px;">
  <div class="row g-0 ">
    <div class="col-md-4 my-5">
      <img src="{{product.image.url}}" class="img-fluid rounded-start" alt="..." height="400px">
    </div>
    <div class="col-md-8">
      <div class="card-body m-3">
        <h5 class="card-title ">{{product.name}}</h5>
        <h5 class="card-title"><i class="fa-solid fa-indian-rupee-sign"></i><i>{{product.price}}</i></h5>
        <p class="card-text">Stock :<i>{{product.stock}}</i> </p>
        <p class="card-text text-secondary">{{product.desc}}</p>
        {% if user.is_superuser == True %}
           {% if product.stock > 0 %}
        <p>Product In stock</p>
        <a href="{% url 'shop:add_stock' product.id %}" class="btn btn-outline-secondary">Add Stock</a>
        {% else %}
        <p>Product Out of stock</p>
        <a href="{% url 'shop:add_stock' product.id %}" class="btn btn-outline-secondary">Add Stock</a>
        {% endif %}


        {% else %}
        {% if product.stock > 0 %}
        <a href="{% url 'cart:cart' product.id %}" class="btn btn-outline-secondary">Add to cart</a>
        {% else %}
        <h5>Out of Stock</h5>
        {% endif %}


        {% endif %}
      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .class1{
    margin:auto;
    border: 1px solid white;
    padding:20px;
    justify-content:space-around;
    align-items:center;}

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div class="class1">
    <img src="{{category.image.url}}" height="750px" width="100%">
</div>
<div class="class1">
    <h1 class="text-center mt-0 text-secondary"><b>{{category.name}}</b></h1>
</div>
<div class="class1">
    <p>{{category.description}}</p>
</div>

<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">
    <div class="container-fluid">
        <div class="row">
        {% for i in product %}
              <div class="col-md-4">
                <article class="post-item card border-1 shadow-sm p-3">
                  <div class="image-holder zoom-effect">
                    <a href="#">
                      <img src="{{i.image.url}}" alt="post" class="card-img-top" height="350px">
                    </a>
                  </div>
                  <div class="card-body text-center">
                    <div class="post-header">
                      <h3 class="post-title">{{i.name}}
                      </h3>
                        <p><i class="fa-solid fa-indian-rupee-sign"></i>{{i.price}}</p>
                        <a href="{% url 'shop:product_details' i.id %}" class="btn btn-outline-secondary ">Details</a>
                    </div>
                  </div>
                </article>
              </div>
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

ecommerce/templates/search_products.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

    {% if product == None %}
    <form></form>
    {% else %}
<h2 class="text-center my-2"  style="font-family: EamesBold;">You have searched for {{query}}</h2>
    <div class="container-fluid">
        <div class="row">
        {% for i in product %}
              <div class="col-md-4">
                <article class="post-item card border-1 shadow-sm p-3 my-1">
                  <div class="image-holder zoom-effect">
                    <a href="#">
                      <img src="{{i.image.url}}" alt="post" class="card-img-top" height="350px">
                    </a>
                  </div>
                  <div class="card-body text-center">
                    <div class="post-header">
                      <h3 class="post-title">{{i.name}}
                      </h3>
                        <p><i class="fa-solid fa-indian-rupee-sign"></i>{{i.price}}</p>
                        <a href="{% url 'shop:product_details' i.id %}" class="btn btn-outline-secondary ">Details</a>
                    </div>
                  </div>
                </article>
              </div>
            {% empty %}
                     <h2 class="text-center my-2"  style="font-family: EamesBold;">No results found</h2>
        {% endfor %}
        </div>
    </div>

    {% endif %}
</section>
{% endblock %}